name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main
    paths:
      - 'src/backend/**'  # Trigger only if files in 'src/backend' are changed

env:
  REG_NAME: "exo.container-registry.com" # Registry name without "azurecr.io"
  IMAGE_NAME: "todo-app" # Image name in ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Connect to registry
        run: |
          docker login -u quentin.badoud@edufr.ch -p ${{ secrets.DOCKER_PASSWORD }} $REG_NAME

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} ./src/backend  # Build context is src/backend

      - name: Tag Docker image
        run: |
          docker tag ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }} ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:PIR

      - name: Push to registry
        run: |
          docker push ${{ env.REG_NAME }}/c213-emf/${{ env.IMAGE_NAME }}:PIR
